version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use a Python image suitable for your requirements

    steps:
      - checkout  # Checkout code from your repository

      # Execute the Python test script using LambdaTest credentials
      - run:
          name: Run Python test script with LambdaTest credentials
          command: |
            python test.py
          environment:
            LT_USERNAME: $LT_USERNAME  # Reference CircleCI environment variable
            LT_ACCESS_KEY: $LT_ACCESS_KEY  # Reference CircleCI environment variable
workflows:
  version: 2
  test_workflow:
    jobs:
      - test
