version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use a Python image suitable for your requirements

    steps:
      - checkout  # Checkout code from your repository
      - run:
          name: install dependecy
          command: |
            pip install selenium  
            


      # Execute the Python test script using LambdaTest credentials
      - run:
          name: Run Python test script with LambdaTest credentials
  
          command: |
            python test.py

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
